---
title: "Washout experiments with toxin immunity modules"
output: html_notebook
---
```{r}
library(ggplot2)
library(dplyr)
library(plater)
library(tidyverse)
library(lubridate) #hms function
library(reshape2)
```

Experimental Plate (Plate2, ran in H1)

```{r}
plate2_outgrowth <- read_csv(file = "/Users/halvorsen1/Documents/RStudio/csv_files/20220428_ColTse_bothWashouts_Plate2_outgrowth.csv")
plate2_washout <- read_csv(file = "/Users/halvorsen1/Documents/RStudio/csv_files/20220428_ColTse_bothWashouts_Plate2_overnight.csv")
plate2_keys <- read_plate(
  "/Users/halvorsen1/Documents/RStudio/csv_files/20220428_ColTse_bothWashouts_Plate2_KEYS.csv",
  well_ids_column = "Key")

plate2_outgrowth <- pivot_longer(plate2_outgrowth, cols = A01:H12, names_to = "Key", values_to = "OD600")
plate2_washout <- pivot_longer(plate2_washout, cols = A01:H12, names_to = "Key", values_to = "OD600")

#Reformat time
y <- hms(plate2_outgrowth$`Time`)
plate2_outgrowth$`Time` <- hour(y) + minute(y) / 60 + second(y) / 360

y <- hms(plate2_washout$`Time`)
plate2_washout$`Time` <- hour(y) + minute(y) / 60 + second(y) / 360

plate2_washout$Time <- round(plate2_washout$Time + 6.5, digits = 2)

plate2 <- rbind(plate2_outgrowth, plate2_washout)

plate2 <- full_join(plate2, plate2_keys, by = "Key")
```

Control Plate (Plate1, ran in HTX)

```{r}
plate1_outgrowth <- read_csv(file = "/Users/halvorsen1/Documents/RStudio/csv_files/20220428_ColTse_bothWashouts_Plate1ctrl_outgrowth.csv")
plate1_washout <- read_csv(file = "/Users/halvorsen1/Documents/RStudio/csv_files/20220428_ColTse_bothWashouts_Plate1ctrl_overnight.csv")
plate1_keys <- read_plate(
  "/Users/halvorsen1/Documents/RStudio/csv_files/20220428_ColTse_bothWashouts_Plate1_KEYS.csv",
  well_ids_column = "Key")

plate1_outgrowth <- pivot_longer(plate1_outgrowth, cols = A01:H12, names_to = "Key", values_to = "OD600")
plate1_washout <- pivot_longer(plate1_washout, cols = A01:H12, names_to = "Key", values_to = "OD600")

#Reformat time
y <- hms(plate1_outgrowth$`Time`)
plate1_outgrowth$`Time` <- hour(y) + minute(y) / 60 + second(y) / 360

y <- hms(plate1_washout$`Time`)
plate1_washout$`Time` <- hour(y) + minute(y) / 60 + second(y) / 360

plate1_washout$Time <- round(plate1_washout$Time + 6.5, digits = 2)

plate1 <- rbind(plate1_outgrowth, plate1_washout)

plate1 <- full_join(plate1, plate1_keys, by = "Key")
```

Experimental Plate, cumate washout:

```{r}
plate2_cum <- plate2 %>%
  filter(washout == 'cumate') %>%
  group_by(Strain, `cumate (mM)`, Time) %>%
  summarise_at(.vars = "OD600", .funs = c(meanOD = mean, sdOD = sd))

# Plot both outgrowth and washout together on 1 graph

strain_names <- c(
                  'TH126' = "Tse2-Tsi2",
                  'TH240' = "Tse2-Tsi2[ssrA]",
                  'TH128' = "Col-ImmE2",
                  'TH237' = "Col-ImmE2[ssrA]")

plate2_cum$Strain <- factor(plate2_cum$Strain,
                         levels = c("TH126", "TH128", "TH240", "TH237"))

cumate_vals <- c(0,0.02,0.07,0.1,0.3,0.5)
discrete_cum <- c("#DBC873", "#C2A464", "#C8B09D", "#AD8E97", "#AC75C1", "#A442C9", "#A442C9")
plate2_cum$`cumate (mM)`<- as.factor(plate2_cum$`cumate (mM)`)

plate2 %>% 
  filter(washout == "cumate")  %>%
  filter(`cumate (mM)` == 0.3 & Replicate == "1") %>%
  ggplot(aes(x = Time, y = OD600, color = Strain , group = Strain)) +
  #facet_wrap(facets = vars(Strain), labeller = strain_names, nrow = 5, ncol = 1) +
  geom_rect(xmin=-.3, 
            xmax=5.5, 
            ymin=-.25, 
            ymax=max(plate2_cum$Time),
            color = NA,
            fill = "gray93", 
            alpha = 0.5) +
  geom_line(size = 1) +  
  geom_point(size = 2) +
  #geom_errorbar(aes(ymin = meanOD-sdOD, ymax = meanOD+sdOD), width = 0.5) +
  scale_color_manual(values = c("TH126" = "#36D81C",
                                "TH128" = "#4796F5",
                               "TH240" = "#40A636",
                               "TH237" = "#4180C9"),
                     labels = strain_names) +
  labs(x = 'Time (hrs)', 
       y = expression('OD'[600]),
       title = "no cumate washout with 1 mM IPTG addition") +
  scale_x_continuous(limits = c(0,25), breaks = seq(0,25,4)) +
  scale_y_continuous(limits = c(0,2), breaks = seq(0,2,0.5)) +
  #scale_color_gradient(low = "#DCCC15", 
  #                     high = "#876493",
  #                     guide = "legend", 
  #                     aesthetics = "color", 
  #                     values = cumate_vals,
  #                     na.value = NA) +
  #scale_colour_brewer(palette = "spectral", direction = -1) +
  theme_bw() +
  theme(strip.background = element_blank(),
        #strip.text.x = element_text(face = "bold", size = 12),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text = element_text(size = 16),
        plot.title = element_text(size = 13, color = "black", face = "bold"),
        legend.text = element_text(size = 14),
        legend.title = element_blank(),
        strip.text.x = element_text(size = 12),
        legend.key.size = unit(0.8, 'cm'),
        axis.title = element_text(size = 14)
          )
```
```{r}
ggsave(filename = "20220428_ColTse_0.3cumate_washout_Plate2.png", path = "/Users/halvorsen1/Documents/R_graphs/Washouts", width = 5.5, height = 3, units = "in", device='png', dpi=300)
```

Experimental Plate, IPTG washout:

```{r}
plate2_IPTG <- plate2 %>%
  filter(washout == 'IPTG') %>%
  group_by(Strain, `IPTG (mM)`, Time) %>%
  summarise_at(.vars = "OD600", .funs = c(meanOD = mean, sdOD = sd))

# Plot both outgrowth and washout together on 1 graph

strain_names <- as_labeller(c(
                  'TH126' = "Tse2-Tsi2",
                  'TH240' = "Tse2-Tsi2[ssrA]",
                  'TH128' = "Col-ImmE2",
                  'TH237' = "Col-ImmE2[ssrA]"))

plate2_IPTG$Strain <- factor(plate2_IPTG$Strain,
                         levels = c("TH126", "TH128", "TH240", "TH237"))

discrete_IPTG <- c("#A442C9", "#AC75C1", "#AD8E97", "#C8B09D", "#C2A464", "#DBC873")
plate2_IPTG$`IPTG (mM)`<- as.factor(plate2_IPTG$`IPTG (mM)`)

plate2$Replicate <- as.character(plate2$Replicate)

plate2 %>% 
  filter(washout == "IPTG") %>%
  filter(`IPTG (mM)` == "0" & Replicate == "1") %>%
  ggplot(aes(x = Time, y = OD600, color = Strain , group = Strain)) +
  #facet_wrap(facets = vars(Strain), labeller = strain_names, nrow = 5, ncol = 1) +
  geom_rect(xmin=-.3, 
            xmax=5.5, 
            ymin=-.25, 
            ymax=max(plate2_cum$Time),
            color = NA,
            fill = "gray93", 
            alpha = 0.5) +
  geom_line(size = 1) +  
  geom_point(size = 2) +
  #geom_errorbar(aes(ymin = meanOD-sdOD, ymax = meanOD+sdOD), width = 0.5) +
  scale_color_manual(values = c("TH126" = "#36D81C",
                                "TH128" = "#4796F5",
                               "TH240" = "#40A636",
                               "TH237" = "#4180C9"),
                     labels = strain_names) +
  labs(x = 'Time (hrs)', 
       y = expression('OD'[600]),
       title = "no IPTG washout with 1 mM cumate addition") +
  scale_x_continuous(limits = c(0,25), breaks = seq(0,25,4)) +
  scale_y_continuous(limits = c(0,2), breaks = seq(0,2,0.5)) +
  #scale_color_gradient(low = "#DCCC15", 
  #                     high = "#876493",
  #                     guide = "legend", 
  #                     aesthetics = "color", 
  #                     values = cumate_vals,
  #                     na.value = NA) +
  #scale_colour_brewer(palette = "spectral", direction = -1) +
  theme_bw() +
  theme(strip.background = element_blank(),
        #strip.text.x = element_text(face = "bold", size = 12),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text = element_text(size = 14),
        text = element_text(size = 12),
        plot.title = element_text(size = 13, color = "black", face = "bold"),
        legend.text = element_text(size = 10),
        legend.title = element_blank(),
        strip.text.x = element_text(size = 12),
        legend.key.size = unit(0.4, 'cm'),
        axis.title = element_text(size = 14)
          )
```

```{r}
ggsave(filename = "20220428_ColTse_0.7IPTG_washout_Plate2.png", path = "/Users/halvorsen1/Documents/R_graphs/Washouts", width = 5, height = 3, units = "in", device='png', dpi=300)
```


Control plate, Cumate washout

```{r}
plate1_cum <- plate1 %>%
  filter(washout == 'cumate') %>%
  group_by(Strain, `cumate (mM)`, Time) %>%
  summarise_at(.vars = "OD600", .funs = c(meanOD = mean, sdOD = sd))

# Plot both outgrowth and washout together on 1 graph

strain_names <- c(
                  'TH126' = "Tse2-Tsi2",
                  'TH240' = "Tse2-Tsi2[ssrA]",
                  'TH128' = "Col-ImmE2",
                  'TH237' = "Col-ImmE2[ssrA]")

plate1_cum$Strain <- factor(plate1_cum$Strain,
                         levels = c("TH126", "TH128", "TH240", "TH237"))

cumate_vals <- c(0,0.02,0.07,0.1,0.3,0.5)
discrete_cum <- c("#DBC873", "#C2A464", "#C8B09D", "#AD8E97", "#AC75C1", "#A442C9", "#A442C9")
plate1_cum$`cumate (mM)`<- as.factor(plate1_cum$`cumate (mM)`)

plate1_cum %>% 
  filter(`cumate (mM)` == 0) %>%
  ggplot(aes(x = Time, y = meanOD, color = Strain , group = Strain)) +
  #facet_wrap(facets = vars(Strain), labeller = strain_names, nrow = 5, ncol = 1) +
  geom_rect(xmin=-.3, 
            xmax=5.5, 
            ymin=-.25, 
            ymax=max(plate1_cum$Time),
            color = NA,
            fill = "gray93", 
            alpha = 0.5) +
  geom_line(size = 1) +  
  geom_point(size = 2) +
  geom_errorbar(aes(ymin = meanOD-sdOD, ymax = meanOD+sdOD), width = 0.5) +
  scale_color_manual(values = c("TH126" = "#36D81C",
                                "TH128" = "#4796F5",
                               "TH240" = "#40A636",
                               "TH237" = "#4180C9"),
                     labels = strain_names) +
  labs(x = 'Time (hrs)', 
       y = expression('OD'[600]),
       title = "no cumate washout with no IPTG addition") +
  scale_x_continuous(limits = c(0,25), breaks = seq(0,25,4)) +
  scale_y_continuous(limits = c(0,2), breaks = seq(0,2,0.5)) +
  #scale_color_gradient(low = "#DCCC15", 
  #                     high = "#876493",
  #                     guide = "legend", 
  #                     aesthetics = "color", 
  #                     values = cumate_vals,
  #                     na.value = NA) +
  #scale_colour_brewer(palette = "spectral", direction = -1) +
  theme_bw() +
  theme(strip.background = element_blank(),
        #strip.text.x = element_text(face = "bold", size = 12),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text = element_text(size = 16),
        plot.title = element_text(size = 13, color = "black", face = "bold"),
        legend.text = element_text(size = 14),
        legend.title = element_blank(),
        strip.text.x = element_text(size = 12),
        legend.key.size = unit(0.8, 'cm'),
        axis.title = element_text(size = 14)
          )
```
Control plate, IPTG

```{r}
plate1_IPTG <- plate1 %>%
  filter(washout == 'IPTG') %>%
  group_by(Strain, `IPTG (mM)`, Time) %>%
  summarise_at(.vars = "OD600", .funs = c(meanOD = mean, sdOD = sd))

# Plot both outgrowth and washout together on 1 graph

strain_names <- as_labeller(c(
                  'TH126' = "Tse2-Tsi2",
                  'TH240' = "Tse2-Tsi2[ssrA]",
                  'TH128' = "Col-ImmE2",
                  'TH237' = "Col-ImmE2[ssrA]"))

plate1_IPTG$Strain <- factor(plate1_IPTG$Strain,
                         levels = c("TH126", "TH128", "TH240", "TH237"))

discrete_IPTG <- c("#A442C9", "#AC75C1", "#AD8E97", "#C8B09D", "#C2A464", "#DBC873")
plate1_IPTG$`IPTG (mM)`<- as.factor(plate1_IPTG$`IPTG (mM)`)

plate1$Replicate <- as.character(plate1$Replicate)

plate1 %>% 
  filter(washout == "cumate") %>%
  filter(`cumate (mM)` == "0.3" & Replicate == "1") %>%
  ggplot(aes(x = Time, y = OD600, color = Strain , group = Strain)) +
  #facet_wrap(facets = vars(Strain), labeller = strain_names, nrow = 5, ncol = 1) +
  geom_rect(xmin=-.3, 
            xmax=5.5, 
            ymin=-.25, 
            ymax=max(plate1_cum$Time),
            color = NA,
            fill = "gray93", 
            alpha = 0.5) +
  geom_line(size = 1) +  
  geom_point(size = 2) +
  #geom_errorbar(aes(ymin = meanOD-sdOD, ymax = meanOD+sdOD), width = 0.5) +
  scale_color_manual(values = c("TH126" = "#36D81C",
                                "TH128" = "#4796F5",
                               "TH240" = "#40A636",
                               "TH237" = "#4180C9"),
                     labels = strain_names) +
  labs(x = 'Time (hrs)', 
       y = expression('OD'[600]),
       title = "no cumate washout with no IPTG addition") +
  scale_x_continuous(limits = c(0,25), breaks = seq(0,25,4)) +
  scale_y_continuous(limits = c(0,2), breaks = seq(0,2,0.5)) +
  #scale_color_gradient(low = "#DCCC15", 
  #                     high = "#876493",
  #                     guide = "legend", 
  #                     aesthetics = "color", 
  #                     values = cumate_vals,
  #                     na.value = NA) +
  #scale_colour_brewer(palette = "spectral", direction = -1) +
  theme_bw() +
  theme(strip.background = element_blank(),
        #strip.text.x = element_text(face = "bold", size = 12),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text = element_text(size = 14),
        text = element_text(size = 12),
        plot.title = element_text(size = 13, color = "black", face = "bold"),
        legend.text = element_text(size = 10),
        legend.title = element_blank(),
        strip.text.x = element_text(size = 12),
        legend.key.size = unit(0.4, 'cm'),
        axis.title = element_text(size = 14)
          )
```
```{r}
ggsave(filename = "20220428_ColTse_0.3_cumate_washout_Plate1.png", path = "/Users/halvorsen1/Documents/R_graphs/Washouts", width = 5, height = 3, units = "in", device='png', dpi=300)
```


```{r}
washout_CFUs <- read.csv(file = "/Users/halvorsen1/Documents/RStudio/csv_files/20220430_ColTse_bothWashouts_EscapeFrequencies.csv")

washout_CFUs$Strain <-factor(washout_CFUs$Strain,
                  levels = c("TH126", "TH128", "TH240", "TH237"))

washout_CFUs$Pre_washout <-factor(washout_CFUs$Pre_washout,
                  levels = c("no cumate", "0.07 mM cumate", "0.3 mM cumate", "no IPTG", "0.3 mM IPTG", "0.7 mM IPTG"))

washout_CFUs[is.na(washout_CFUs)] <- 0
washout_CFUs$Escape_freq <- as.numeric(washout_CFUs$Escape_freq)

washout_CFUs %>% 
  filter(Pre_washout == "0.7 mM IPTG" & Post_washout == "1 mM cumate") %>%
  #filter(Pre_washout == "0.3 mM cumate") %>%
  ggplot(aes(x = as.character(Time), y = Escape_freq, fill = Strain)) +
  geom_bar(position = "dodge",
           stat = "identity",
           size = 1, 
           color = "black") +
  #facet_grid(~ Pre_washout, space = "free_x", scales = "free_x", switch="x") +
  labs(y="survival ratio",
       x = "IPTG",
       title = "0.7 mM IPTG washout > 1 mM cumate") +
  scale_fill_manual(values = c("TH126" = "#36D81C",
                               "TH128" = "#4796F5",
                               "TH240" = "yellow",
                               "TH237" = "purple"),
                     labels = strain_names) +
  scale_y_log10(
    breaks = scales::trans_breaks("log10", function(x) 10^x),
    labels = scales::trans_format("log10", scales::math_format(10^.x))) +
  #scale_x_discrete(labels = strain_names) +
  geom_vline(xintercept = c(1.5), size = 0.5) +
  geom_hline(yintercept = 1, color = "black") +
  theme_classic() +
  theme(text = element_text(size = 12),
        strip.background = element_blank(),
        panel.spacing.x = unit(2, "lines"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title = element_text(color = "black", face = "bold", size = 11),
        axis.text = element_text(size = 14), 
        strip.text = element_text(face = "bold", size = 10),
        legend.position = "right",
        legend.title = element_blank(),
        axis.text.x = element_text(size = 12),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size = 14))

```

```{r}
ggsave(filename = "20220428_ColTse_washouts_CFUs_ctrl_0.7IPTG.png", path = "/Users/halvorsen1/Documents/R_graphs/Escape_mutants", width = 5.5, height = 4, units = "in", device='png', dpi=300)
```