---
title: "Escape frequencies for kill switches"
output: pdf_document
---

```{r echo=FALSE}
library(ggplot2)
library(dplyr)
library(plater)
library(tidyverse)
library(lubridate) #hms function
library(reshape2)
```


```{r echo=FALSE}
CFUs <- read.csv(file = 
                   "/Users/halvorsen1/SFA_killswitches/data/escape/20220420_EscapeFrequencies_SBW25_HST01_IPTG+-.csv")

CFUs[is.na(CFUs)] <- 0

std <- function(x) sd(x)/sqrt(length(x))

CFU_ND <- CFUs %>%
  filter(CFU_nonperm == 0)

CFU_ND <- CFU_ND %>%
  group_by(Species, Strain, Pre_growth) %>%
  summarize_at(.vars = vars(Escape_freq), .funs = c(meanFreq = mean, 
                                                    stdFreq = std))

CFU_ND[is.na(CFU_ND)] <- 0

CFUs_means <- CFUs %>%
  group_by(Species, Strain, Pre_growth) %>%
  summarize_at(.vars = vars(Escape_freq), .funs = c(meanFreq = mean, 
                                                    stdFreq = std))
CFUs_means[is.na(CFUs_means)] <- 0


CFU_merge <- rbind(CFUs_means, CFU_ND)
  

CFUs_means$Strain <- factor(CFUs_means$Strain,
                            levels = c("TH86",
                                       "TH88",
                                       "TH99",
                                       "TH100",
                                       "TH131",
                                       "TH126",
                                       "TH128",
                                       "TH98",
                                       "TH124",
                                       "TH214",
                                       "TH203",
                                       "TH48",
                                       "TH52",
                                       "TH81",
                                       "TH82",
                                       "SJC038",
                                       "TH109",
                                       "TH107",
                                       "TH80",
                                       "TH121",
                                       "TH213",
                                       "TH181"))

strain_names <- as_labeller(c('TH37' = "wild type",
                  'TH86' = "regulators only",
                  'TH88' = "CcdB-CcdA",
                  'TH99' = "HicA-HicB",
                  'TH100' = "ParE-ParD",
                  'TH98' = "EcoRI-EcoRIM",
                  'TH124' = "EcoRI\nno methylase",
                  'TH126' = "Tse2-Tsi2",
                  'TH128' = "colicin E2\nImmE2",
                  'TH131' = "RelE-RelB",
                  "TH203" = "TisB\nno antitoxin",
                  "TH214" = "TisB-IstR1",
                  "TH80" = "EcoRI-EcoRIM",
                  "TH121" = "EcoRI/nno methylase",
                  "TH213" = "TisB-IstR",
                  "TH181" = "TisB/no antitoxin"
                  ))

expSup <- function(w, digits=0) {
  sprintf(paste0("%.", digits, "f*x*10^%d"), w/10^floor(log10(abs(w))), floor(log10(abs(w))))
}

Eco_TisB_coli_raw <- CFUs %>%
    filter(Species == "HST01") %>%
  filter(Pre_growth == "IPTG+") %>%
  filter(Strain == "TH80" | Strain == "TH121" | Strain == "TH213" | Strain == "TH181")


Eco_TisB_coli_means <- CFUs_means %>% 
  filter(Species == "HST01") %>%
  filter(Pre_growth == "IPTG+") %>%
  filter(Strain == "TH80" | Strain == "TH121" | Strain == "TH213" | Strain == "TH181")

Eco_TisB_coli_raw$Strain <- factor(Eco_TisB_coli_raw$Strain,
                                     levels = c("TH80",
                                                "TH121",
                                                "TH213",
                                                "TH181"))
ggplot() +
  geom_col(data = Eco_TisB_coli_means, mapping = aes(x = Pre_growth, y = log10(meanFreq), fill = Strain, width = 0.7)) +
  geom_point(data = Eco_TisB_coli_raw, aes(x = Pre_growth, y = log10(Escape_freq)), size = 3) +
  facet_wrap(~Strain, nrow = 1, ncol = 11, labeller = strain_names) +
  labs( y=expression('log'[10]*' survival ratio'),
        x = "") +
  geom_errorbar(data = Eco_TisB_coli_means, aes(x = Pre_growth, y = log10(meanFreq), ymin = log10(meanFreq-stdFreq), ymax = log10(meanFreq+stdFreq)), width = 0.4) +
  scale_y_continuous(breaks = c(0,-1,-2,-3,-4,-5,-6,-7)) +
  scale_fill_manual(values = c(
                                "TH80" = "#30ECEC",
                                "TH121" = "#30ECEC",
                                "TH213" = "#D4BFDB",
                                "TH181" = "#D4BFDB")) +
  # scale_y_log10(
  #   breaks = scales::trans_breaks("log10", function(x) 10^x),
  #   labels = scales::trans_format("log10", scales::math_format(10^.x))) +
  #scale_x_discrete(labels = IPTG_axis) +
  geom_vline(xintercept = c(5.5, 7.5), size = 0.3) +
  geom_hline(yintercept = 0, color = "black") +
  theme_classic() +
  theme(text = element_text(size = 12),
        strip.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.spacing.x = unit(0.003, "lines"),
        plot.title = element_text(color = "black", face = "bold", size = 14),
        axis.text = element_text(size = 14), 
        strip.text = element_text(size = 12),
        legend.position = "none",
        legend.title = element_text(size = 12),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size = 14),
        panel.grid.major.x = element_blank())

```

```{r echo=FALSE}
ggsave(filename = "20220420_EscapeFrequencies_HST01_Eco_Tis.png", path = "/Users/halvorsen1/SFA_killswitches/results/figures", width = 6.5, height = 4, units = "in", device='png', dpi=300)
```


```{r echo=FALSE}

strain_names <- as_labeller(c('TH48' = "regulators only",
                  'TH52' = "CcdB-CcdA",
                  'TH81' = "HicA-HicB",
                  'TH82' = "ParE-ParD",
                  'TH121' = "EcoRI\nno methylase",
                  'TH109' = "Tse2-Tsi2",
                  'TH107' = "colicin E2\nImmE2",
                  'SJC038' = "RelE-RelB",
                  "TH213" = "TisB-IstR",
                  "TH80" = "EcoRI-EcoRIM",
                  "TH181" = "TisB\nno antitoxin"
                  ))

IPTG_axis <- c("IPTG+" = "+",
               "IPTG-" = "-")

CFUs_means %>% 
  filter(Species == "HST01") %>%
  ggplot(aes(x = Pre_growth, y = log10(meanFreq), fill = Strain)) +
  geom_col() +
  facet_wrap(~Strain, nrow = 1, ncol = 11, labeller = strain_names) +
  labs( y=expression('log'[10]*' survival ratio')) +
  geom_errorbar(aes(ymin = log10(meanFreq-stdFreq), ymax = log10(meanFreq+stdFreq)), width = 0.4) +
  scale_fill_manual(values = c("TH46" = "gray",
                                "TH52" = "#EC5E8D",
                                "TH81" = "#D7A3EC",
                                "TH82" = "#E0D935",
                                "SJC038" = "#F7AB37",
                                "TH109" = "#36D81C",
                                "TH107" = "#4796F5",
                                "TH80" = "#30ECEC",
                                "TH121" = "#30ECEC",
                                "TH213" = "#D4BFDB",
                                "TH181" = "#D4BFDB")) +
  # scale_y_log10(
  #   breaks = scales::trans_breaks("log10", function(x) 10^x),
  #   labels = scales::trans_format("log10", scales::math_format(10^.x))) +
  scale_x_discrete(labels = IPTG_axis) +
  geom_vline(xintercept = c(5.5, 7.5), size = 0.3) +
  geom_hline(yintercept = 1, color = "black") +
  theme_classic() +
  theme(text = element_text(size = 12),
        strip.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title = element_text(color = "black", face = "bold", size = 14),
        axis.text = element_text(size = 14), 
        strip.text = element_text(size = 12, angle = 90, vjust = 0.5, hjust = 0.05),
        legend.position = "none",
        legend.title = element_text(size = 12),
        axis.text.x = element_text(size = 15, vjust = 0.5),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size = 14))
```

```{r echo=FALSE}
ggsave(filename = "20220420_EscapeFrequencies_HST01_combined.png", path = "/Users/halvorsen1/SFA_killswitches/results/figures", width = 6.5, height = 4, units = "in", device='png', dpi=300)
```